[project]
name = "comfyui-image-and-video-saver"
description = "Save images and videos with Civitai-compatible generation metadata in ComfyUI."
version = "1.25.0"
license = { file = "LICENSE" }
dependencies = ["piexif"]

[project.urls]
Repository = "https://github.com/diodiogod/ComfyUI-Image-and-Video-Saver"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "diodiogod"
DisplayName = "ComfyUI Image & Video Saver"
Icon = ""
